openapi: 3.0.0
info:
  title: Basic Info API
  description: API 用於獲取基本資訊
  version: 1.0.0
servers:
  - url: http://intro-swagger.com

paths:
  /api/basicInfo-CH:
    get:
      summary: 獲取基本資訊
      description: 獲取所有基本資訊，或通過指定 id 獲取特定的基本資訊
      parameters:
        - name: id
          in: query
          description: 基本資訊的 id
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: 成功獲得資料
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
        "204":
          description: 無內容
        "404":
          description: 找不到內容
        "500":
          description: 內部伺服器錯誤

    post:
      summary: 新增基本資訊
      description: 使用 POST 方法新增一筆基本資訊
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  description: 基本資訊的 id
                  example: 1234
                name:
                  type: string
                  description: 名稱
                  example: 名稱
                description:
                  type: string
                  description: 描述 (選填)
                  example: 描述
              required:
                - id
                - name
      responses:
        "200":
          description: 成功新增資料
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  description:
                    type: string
        "400":
          description: 無效的輸入
        "500":
          description: 內部伺服器錯誤
